{% set name = "spyder-kernels" %}
{% set version = "3.0.0b1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/spyder-kernels-{{ version }}.tar.gz
  sha256: d1a364ab89da716d91671ba9d89ef8f1966068bba0e470797a489653829caaf3

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  string: "unix_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"  # [unix]
  string: "win_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"   # [win]

requirements:
  host:
    - python >=3.7
    - pip
    - setuptools
  run:
    - python >=3.7
    - cloudpickle
    - ipykernel >=6.16.1,<7.0.0
    - ipython >=7.31.1,<9.0.0,!=8.8.0,!=8.9.0,!=8.10.0,!=8.11.0,!=8.12.0,!=8.12.1
    - jupyter_client >=7.4.9,<9.0.0
    - pyzmq >=22.1.0
    - pyxdg >=0.26  # [unix]
    - wurlitzer >=1.0.3  # [unix]
    - __unix  # [unix]
    - __win   # [win]

test:
  imports:
    - spyder_kernels
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://www.spyder-ide.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Jupyter kernels for Spyder's console

  description: |
    Provides Jupyter kernels for use with the consoles of Spyder, the
    Scientific Python Development Environment. These can launched either
    through Spyder itself or in an independent Python session, and allow for
    interactive or file-based execution of Python code in different
    environments, all inside the IDE.
    For more on Spyder, visit https://www.spyder-ide.org/

    To learn about creating, connecting and using Spyder's consoles, read:
    https://docs.spyder-ide.org/ipythonconsole.html

    For advice on managing packages and environments with Spyder, see:
    https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder
  doc_url: https://docs.spyder-ide.org/
  dev_url: https://github.com/spyder-ide/spyder-kernels

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
