{% set name = "spyder-kernels" %}
{% set python_min = "3.8" %}
{% set version = "3.0.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name.replace('-', '_') }}-{{ version }}.tar.gz
  sha256: 63cf9da6ea533679a5a791211e958cb4a7ebb803f84086fbdc248c08a7914669

build:
  script: {{ PYTHON }} -m pip install . -vv
  number: 0
  noarch: python
  string: "unix_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"  # [unix]
  string: "win_pyh{{ PKG_HASH }}_{{ PKG_BUILDNUM }}"  # [win]

requirements:
  host:
    - python {{ python_min }}
    - pip
    - setuptools
  run:
    - python >={{ python_min }}
    - cloudpickle
    - ipykernel >=6.29.3,<7.0.0
    - ipython >=8.12.2,<9.0.0,!=8.17.1
    - jupyter_client >=7.4.9,<9.0.0
    - pyxdg >=0.26  # [unix]
    - pyzmq >=24.0.0
    - wurlitzer >=1.0.3  # [unix]
    - __unix  # [unix]
    - __win   # [win]

test:
  imports:
    - spyder_kernels
  commands:
    - pip check
  requires:
    - python {{ python_min }}
    - pip

about:
  home: https://www.spyder-ide.org/
  license: MIT
  license_family: MIT
  license_file: LICENSE.txt
  summary: Jupyter kernels for Spyder's console

  description: |
    Provides Jupyter kernels for use with the consoles of Spyder, the
    Scientific Python Development Environment. These can launched either
    through Spyder itself or in an independent Python session, and allow for
    interactive or file-based execution of Python code in different
    environments, all inside the IDE.
    For more on Spyder, visit https://www.spyder-ide.org/

    To learn about creating, connecting and using Spyder's consoles, read:
    https://docs.spyder-ide.org/ipythonconsole.html

    For advice on managing packages and environments with Spyder, see:
    https://github.com/spyder-ide/spyder/wiki/Working-with-packages-and-environments-in-Spyder
  doc_url: https://docs.spyder-ide.org/
  dev_url: https://github.com/spyder-ide/spyder-kernels

extra:
  recipe-maintainers:
    - ccordoba12
    - dalthviz
