appveyor:
  secure: {BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1}
compiler_stack: comp7
max_py_ver: '37'
max_r_ver: '35'
travis:
  secure: {BINSTAR_TOKEN: na+VvwQxQF8Ah8bvRTE/9kAr5gtoXMF0fCHbhE8HUwTQdBE/skJSe171dsiVIii/d/wr81WJiJ5h3zdlHAZn7k9G8QYrljsuNx0maZPEU3QF02tp6R6f4tGUoi0ENj7i47ZoNTFWAFmFqPN9lWDpcFJ3T7+R2Da/yQpvrIffHnRvwdv23/NsopoGTUQ2fXJVK1jbP3ZRv0SI90LLRZzlT50P31FvTtTWAImRp00uhuo8brmklySUi/yH92yo3S28jiZ1lkvFucTZ/tgQ/Yb8TUZXrKv7ptNQINDYt4oaPc9TTtzEURyJz+hfmEEfuThAJaGgp+vup+3HdCpJNtP/VeV5nFD3MT7anfzm17WlAc/GJ37qmtFwr90PuHrXF3I+YGEi7Ohwqevbv5DFdBBZfi6fl1jQSVDllTx/90eF4wrarcHebpBQIJjVROOH45FGFMz+K198g1QdPm2Dyg2jFlP73FEabyZOVqMBlIr9JN24MbcOLnyFIkfkosf/ySnTQa1NpAyXPz5izOMN7ig89tt2hi1XcW1YHkU3y0CB3AAZGEtJ6oqL6GTyw35OIDW3laJTrh2d5OzuPZGC00Wc+s9+MAJdO5kKwTKV+V4Fn03F1sHsJ4uQhcHbDNC6TZyOb+XMOLQYRdh9cBQ3oil+upclUmoE7A+ibZa4Aoaj6d4=}
